name: Threadpool Benchmark
on:
  workflow_dispatch:
  push:
    branches:
      - master

permissions:
  contents: write
  deployments: write

jobs:
  benchmark:
    name: Run JavaScript benchmark example
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: pnpm/action-setup@v2
        with:
          version: "latest"
      - uses: actions/setup-node@v3
        with:
          node-version: "18"
      - name: Run benchmark
        run:
          pnpm install && pnpm run build && cd benchmarks && pnpm install && pnpm run run:threadpool | tee ./output.txt

      - name: Store benchmark result
        uses: benchmark-action/github-action-benchmark@v1
        with:
          name: Threadpool Benchmark
          tool: "benchmarkjs"
          output-file-path: benchmarks/output.txt
          github-token: ${{ secrets.GITHUB_TOKEN }}
          auto-push: true
          # Show alert with commit comment on detecting possible performance regression
          alert-threshold: "200%"
          comment-on-alert: true
          fail-on-alert: true
          alert-comment-cc-users: "@snuffyDev"
